'
@startuml tbl_bc_PropertyMaster
entity "BoloSQL_dev.dbo.tbl_bc_PropertyMaster" as tbl_bc_PropertyMaster {
  u2_id: varchar(255), not null
  shadow_key: varchar(20)
  cc_type: varchar(20)
  has_compl: varchar(5)
  category: varchar(20)
  cc_name: varchar(98)
  acquisition: varchar(20)
  acq_descr: varchar(29)
  eff_date: datetime
  acq_summ_grp: varchar(50)
  state: varchar(20)
  county_name: varchar(25)
  cnty_cd: varchar(20)
  fieldid: varchar(20)
  fieldname: varchar(30)
  operator: varchar(20)
  oper_name: varchar(41)
  api_well_no: varchar(20)
  prop_type: varchar(20)
  status: varchar(20)
  status_eff_dates: datetime
  legal_desc_id: varchar(20)
  sections: varchar(20)
  townships: varchar(20)
  ranges: varchar(20)
  sec_descs: varchar(81)
  total_depth: numeric(8,0)
  cnv_id: varchar(20), not null
  has_jib_deck: varchar(1)
  has_rev_deck: varchar(1)
  has_master_deck: varchar(1)
  lease_shadow: varchar(20)
  lease_cc_name: varchar(98)
  area_shadow: varchar(20)
  area_cc_name: varchar(98)
  fmn_shadow: varchar(20)
  fmn_cc_name: varchar(98)
  eng_shadow: varchar(20)
  eng_cc_name: varchar(98)
  supt_shadow: varchar(20)
  supt_cc_name: varchar(98)
  op_shadow: varchar(20)
  op_cc_name: varchar(98)
  co_shadow: varchar(20)
  co_cc_name: varchar(98)
  system_date: datetime
  system_time: varchar(20)
  system_user_id: varchar(20)
  created_date: datetime
  created_time: varchar(20)
  created_by: varchar(20)
  max_trans: datetime
  max_og_sale: datetime
  max_billable: datetime
  max_pr: datetime
  price_idx: varchar(10)
  reg_id: varchar(1690)
  reg_name: varchar(98)
  tx_distr: varchar(20)
  tx_rrc_fld: varchar(33)
  tx_cmgl_no: varchar(20)
  distr: varchar(20)
  unc_link: varchar(239)
  lgcy_nri: decimal(9,8)
  rev_deck_count: int
  master_nri: decimal(9,8)
  lgcy_wi: decimal(9,8)
  jib_deck_count: int
  oil_pur: varchar(50)
  jupiter_wi: decimal(9,8)
  jupiter_nri: decimal(9,8)
  gas_pur: varchar(50)
  liq_pur: varchar(50)
  exp_date: datetime
  coding_flag: varchar(20)
  max_oil_acctg: datetime
  max_gas_acctg: datetime
  max_liq_acctg: datetime
  formation: varchar(25)
  region: varchar(50)
  utlease: varchar(20)
  ut_rrc_id: varchar(20)
  fed_lse_id: varchar(20)
  pumper: varchar(20)
  pumper_desc: varchar(27)
  jib_cc: varchar(20)
  rev_cc: varchar(20)
  max_oil_pdn: datetime
  max_gas_pdn: datetime
  max_liq_pdn: datetime
  3roc: varchar(1)
  lat_long: varchar(30)
  battery: varchar(32)
  supt2: varchar(20)
  oilprod: numeric(38,2)
  oilsales: numeric(38,2)
  waterprod: numeric(38,2)
  wtr_injected: numeric(13,2)
  gas_prdn: numeric(38,2)
  gas_sales: numeric(38,2)
  gas_inj: numeric(13,2)
  gas_lu: numeric(12,2)
  gas_flare: numeric(12,2)
  termination_date: datetime
  termination_remarks: varchar(240)
  termination_type: varchar(20)
  tr_wellid: varchar(15)
  cc_grp: varchar(255)
  cc_grp_desc: varchar(41)
  t_d: real
  prop_oil_pur: varchar(50)
  prop_gas_pur: varchar(50)
  prop_liq_pur: varchar(50)
  typ_wi_lgcy: decimal(9,8)
  typ_ri_lgcy: decimal(9,8)
  typ_or_lgcy: decimal(9,8)
  typ_oth_lgcy: decimal(9,8)
  only_inactives: varchar(10)
  only_pa: varchar(10)
  rv_gb: varchar(20)
  rv_po: varchar(20)
  jb_po: varchar(20)
  pot1202: varchar(20)
  pot1202_gb: varchar(20)
  jupiter_grp: varchar(255)
  jupiter_grp_desc: varchar(41)
  de_grp: varchar(255)
  de_grp_desc: varchar(41)
  company: varchar(20)
  pumper_true: varchar(20)
  pumper_desc_true: varchar(27)
  user_code1: varchar(20)
  pumper_type: int
  mpl_comments: varchar(1690)
  acq_bolt_on: varchar(1690)
  spud_date: datetime
  completion_date: datetime
  phdid: nvarchar(510)
  prev_prop_type: varchar(20)
  prev_stat: varchar(20)
  prev_stat_eff_date: datetime
  mgmt_rollup: varchar(30)
  orri_grp: varchar(255)
  orri_grp_desc: varchar(41)
  beat_ag: varchar(20)
  hz_nonop_grp: varchar(255)
  hz_nonop_grp_desc: varchar(41)
}
@enduml